# Welcome to Jekyll!
#

# Site settings
title: ИКРОМОБИЛЬ72
description: |
  ИКРА КРАСНАЯ (ИКРА ГОРБУШИ)  
  С КАМЧАТКИ (ОХЛАЖДЕННЫЙ ПРОДУКТ)  
  ДОСТАВКА ПО ТЮМЕНИ [+ 7 982 933 6500](tel://+79829336500])
owner: сервис доставки красной икты в Тюмени # or company name
first_published: 2017-2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  instagram: https://twitter.com/<username>
  facebook-official: https://facebook.com/<username>
  vk: https://plus.google.com/u/0/+<username>
  email: /contact/
  
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

theme: jekyll-theme-dinky